--
-- PostgreSQL database dump
--

\restrict lx5q6KWibaNwcXINGxO33XiQdCs8GZbTfEbPSr6MiixkOHg2BVULcsxPktXtaFX

-- Dumped from database version 16.15
-- Dumped by pg_dump version 16.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: entity_resources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.entity_resources (
    id integer NOT NULL,
    entity_id_ref integer,
    entity_type text NOT NULL,
    entity_id text NOT NULL,
    item_id text NOT NULL,
    count integer NOT NULL,
    CONSTRAINT entity_resources_count_positive CHECK ((count > 0))
);


--
-- Name: entity_resources_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.entity_resources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entity_resources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: processed_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.processed_events (
    event_id text NOT NULL,
    scope text NOT NULL,
    response text NOT NULL,
    created_at timestamp without time zone NOT NULL
);


--
-- Name: resource_entities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resource_entities (
    id integer NOT NULL,
    entity_type text NOT NULL,
    entity_id text NOT NULL
);


--
-- Name: resource_entities_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resource_entities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resource_entities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resource_points; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resource_points (
    point_id text NOT NULL,
    room_id text NOT NULL,
    resource text NOT NULL,
    amount integer DEFAULT 0 NOT NULL,
    max_amount integer NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    CONSTRAINT resource_points_amount_valid CHECK (((amount >= 0) AND (amount <= max_amount)))
);


--
-- Name: resource_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resource_transactions (
    transaction_id text NOT NULL,
    event_id text,
    type text NOT NULL,
    source text,
    target text,
    items_transferred text NOT NULL,
    status text NOT NULL,
    created_at timestamp without time zone NOT NULL
);


--
-- Name: schema_info; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_info (
    version integer DEFAULT 0 NOT NULL
);


--
-- Name: entity_resources entity_resources_entity_type_entity_id_item_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entity_resources
    ADD CONSTRAINT entity_resources_entity_type_entity_id_item_id_key UNIQUE (entity_type, entity_id, item_id);


--
-- Name: entity_resources entity_resources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entity_resources
    ADD CONSTRAINT entity_resources_pkey PRIMARY KEY (id);


--
-- Name: processed_events processed_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.processed_events
    ADD CONSTRAINT processed_events_pkey PRIMARY KEY (event_id);


--
-- Name: resource_entities resource_entities_entity_type_entity_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_entities
    ADD CONSTRAINT resource_entities_entity_type_entity_id_key UNIQUE (entity_type, entity_id);


--
-- Name: resource_entities resource_entities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_entities
    ADD CONSTRAINT resource_entities_pkey PRIMARY KEY (id);


--
-- Name: resource_points resource_points_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_points
    ADD CONSTRAINT resource_points_pkey PRIMARY KEY (point_id);


--
-- Name: resource_points resource_points_room_id_resource_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_points
    ADD CONSTRAINT resource_points_room_id_resource_key UNIQUE (room_id, resource);


--
-- Name: resource_transactions resource_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_transactions
    ADD CONSTRAINT resource_transactions_pkey PRIMARY KEY (transaction_id);


--
-- Name: entity_resources_entity_type_entity_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX entity_resources_entity_type_entity_id_index ON public.entity_resources USING btree (entity_type, entity_id);


--
-- Name: resource_points_room_id_resource_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX resource_points_room_id_resource_index ON public.resource_points USING btree (room_id, resource);


--
-- Name: resource_transactions_event_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX resource_transactions_event_id_index ON public.resource_transactions USING btree (event_id);


--
-- Name: entity_resources entity_resources_entity_id_ref_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entity_resources
    ADD CONSTRAINT entity_resources_entity_id_ref_fkey FOREIGN KEY (entity_id_ref) REFERENCES public.resource_entities(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict lx5q6KWibaNwcXINGxO33XiQdCs8GZbTfEbPSr6MiixkOHg2BVULcsxPktXtaFX

