--
-- PostgreSQL database dump
--

\restrict 3aCZLEz1ruasiXlb6c29eCvBJFHetvnN5TR7BYaRikr1iJccAsaVhBD2FbgKxcn

-- Dumped from database version 16.15
-- Dumped by pg_dump version 16.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: processed_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.processed_events (
    event_id text NOT NULL,
    scope text NOT NULL,
    response text NOT NULL,
    created_at timestamp without time zone NOT NULL
);


--
-- Name: schema_info; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_info (
    version integer DEFAULT 0 NOT NULL
);


--
-- Name: zombie_instances; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.zombie_instances (
    zombie_id text NOT NULL,
    type_id text NOT NULL,
    lobby_id text NOT NULL,
    health integer NOT NULL,
    room_id text,
    status text DEFAULT 'idle'::text NOT NULL,
    phase text DEFAULT 'day'::text NOT NULL,
    target_player_id text,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: zombie_inventory_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.zombie_inventory_items (
    id integer NOT NULL,
    zombie_id text NOT NULL,
    item_id text NOT NULL,
    count integer NOT NULL,
    CONSTRAINT zombie_inventory_items_count_positive CHECK ((count > 0))
);


--
-- Name: zombie_inventory_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.zombie_inventory_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zombie_inventory_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zombie_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.zombie_types (
    type_id text NOT NULL,
    name text NOT NULL,
    health integer DEFAULT 100 NOT NULL,
    damage integer DEFAULT 0 NOT NULL,
    speed double precision DEFAULT 1.0 NOT NULL,
    loot_table_id text,
    behaviours text DEFAULT '[]'::text NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: processed_events processed_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.processed_events
    ADD CONSTRAINT processed_events_pkey PRIMARY KEY (event_id);


--
-- Name: zombie_instances zombie_instances_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zombie_instances
    ADD CONSTRAINT zombie_instances_pkey PRIMARY KEY (zombie_id);


--
-- Name: zombie_inventory_items zombie_inventory_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zombie_inventory_items
    ADD CONSTRAINT zombie_inventory_items_pkey PRIMARY KEY (id);


--
-- Name: zombie_inventory_items zombie_inventory_items_zombie_id_item_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zombie_inventory_items
    ADD CONSTRAINT zombie_inventory_items_zombie_id_item_id_key UNIQUE (zombie_id, item_id);


--
-- Name: zombie_types zombie_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zombie_types
    ADD CONSTRAINT zombie_types_pkey PRIMARY KEY (type_id);


--
-- Name: zombie_instances_lobby_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX zombie_instances_lobby_id_index ON public.zombie_instances USING btree (lobby_id);


--
-- Name: zombie_instances_type_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX zombie_instances_type_id_index ON public.zombie_instances USING btree (type_id);


--
-- Name: zombie_instances zombie_instances_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zombie_instances
    ADD CONSTRAINT zombie_instances_type_id_fkey FOREIGN KEY (type_id) REFERENCES public.zombie_types(type_id) ON DELETE RESTRICT;


--
-- Name: zombie_inventory_items zombie_inventory_items_zombie_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zombie_inventory_items
    ADD CONSTRAINT zombie_inventory_items_zombie_id_fkey FOREIGN KEY (zombie_id) REFERENCES public.zombie_instances(zombie_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict 3aCZLEz1ruasiXlb6c29eCvBJFHetvnN5TR7BYaRikr1iJccAsaVhBD2FbgKxcn

